-- contents 表
CREATE TABLE IF NOT EXISTS contents (
    id BIGINT NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    slug VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'draft',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_contents_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- banners 表
CREATE TABLE IF NOT EXISTS banners (
    id BIGINT NOT NULL PRIMARY KEY,
    image_url VARCHAR(512) NOT NULL,
    link_type VARCHAR(16) NOT NULL DEFAULT 'content',
    link_value VARCHAR(512) NOT NULL DEFAULT '',
    title VARCHAR(255) NOT NULL DEFAULT '',
    position VARCHAR(32) NOT NULL DEFAULT 'home',
    sort_order INT NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
